#!/bin/bash

emojilist=( ":zero:" ":one:" ":two:" ":three:" ":four:" ":five:" ":six:" ":seven:" ":eight:" ":bomb:" )
height=5
width=15
bombfrequency=20
if ( [ "$#" == "1" ] || [ "$#" == "3" ] ) && [ "$1" -gt "0" ] && [ "$1" -lt "11" ]; then
	bombfrequency=$(echo "scale=0; (30/($1))/1"|bc -l)
fi

if [ "$#" == "3" ] && [ "$2" -gt "0" ] && [ "$3" -gt "0" ]; then
	width=$2
	height=$3
fi
i=0
j=0
k=0
pass=0
# smaller number higher difficulty
# pass zero for bombs pass 1 for numbers
minesweepbuffer=()
while [ "$pass" -lt "2" ]
do
	i=0
	while [ "$i" -lt "$height" ]
	do
		j=0
		while [ "$j" -lt "$width" ]
		do
	#		echo "$pass"
			let k=$width+1
			let k=$k*i+$j
			thischar="||${emojilist[0]}||"
			if [ "$pass" == "0" ]; then
				if [ "$(echo $(($RANDOM % $bombfrequency)))" == "0" ]; then
					thischar="||${emojilist[9]}||"
				fi
			elif [ "$pass" == "1" ]; then
				if [ "${minesweepbuffer[$k]}" == "||${emojilist[0]}||" ]; then
					number=0
					y=-1
					while [ "$y" -lt "2" ]
					do
						x=-1
						while [ "$x" -lt "2" ]
						do
							index=0
							columnindex=0
							rowindex=0
							let columnindex=$j+$x
							let rowindex=$y+$i
							let index=($width+1)*$y+$k+$x

							if [ "$columnindex" -gt "-1" ] &&\
		 [ "$rowindex" -gt "-1" ] && [ "$columnindex" -lt "$width" ] && \
			[ "$rowindex" -lt "$height" ] && [ "${minesweepbuffer[$index]}" == "||${emojilist[9]}||" ]; then
								let number=$number+1
							fi
#							echo "$x $y $number ${minesweepbuffer[$index]}"
							let x=x+1
						done
						let y=$y+1
					done
					thischar="||${emojilist[$number]}||"
					#echo "$thischar"
				else
					thischar="||${emojilist[9]}||"
				fi
			fi

			minesweepbuffer[$k]="$thischar"
			let j=$j+1
		done
		let k=$k+1
		minesweepbuffer[$k]=$'\n'
		let i=$i+1
	done
	let pass=$pass+1
done

echo "${minesweepbuffer[@]}" | sed -e "s/\ //g" | sed -e "s/0/ /g"
